Rewind/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('main.urls')),
]

main/urls.py
from django.urls import path, re_path

from . import views

app_name = 'main'
urlpatterns = [
    path('home/<int:pk>/', views.deck, name='deck'),
    path('home/', views.home, name='home'),
    path('video/<int:pk>/', views.video, name='video'),
    path('card/<int:pk>/', views.card, name='card'),
    path('', views.index, name='index'),
    path('youtube_learning/', views.youtube_learning, name='youtube_learning'),
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path("addcard/", views.addcard, name="addcard"),
    path(r'review/<str:type>/<int:pk>/', views.review, name="review"),
    re_path(r'review/deck|video/[0-9]+/question_answer/$', views.question_answer, name="question_answer"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta, datetime
from django.utils import timezone
NEW = "N"
REVIEW = "R"
LEARNING = "L"
FINISHED = "F"

class Deck(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	deck_name = models.CharField(max_length=30)

	def get_due_new_num(self):
		card_list = self.card_set.all()
		(review, learning, new) = Card.card_list_state_count(card_list)
		return review + learning, new


	def get_youtube_videos(self):
		card_list = self.card_set.all()
		youtube_id_set = set()
		for card in card_list:
			youtube_id_set.add(card.youtube.id)

		youtube_list = Youtube.objects.filter(pk__in=list(youtube_id_set))

		videos = []
		for youtube in youtube_list:
			card_list_by_youtube = youtube.card_set.all()
			(review, learning, new) = Card.card_list_state_count(card_list_by_youtube)
			videos.append([youtube, review + learning, new])
		return videos


	def __str__(self):
		return self.deck_name

class Youtube(models.Model):
	deck = models.ForeignKey(Deck, on_delete=models.CASCADE)
	youtube_link = models.URLField()
	youtube_title = models.CharField(max_length=150)

	def __str__(self):
		return self.youtube_title

class Card(models.Model):
	STATE = [(NEW, "NEW"), (REVIEW, "REVIEW"), (LEARNING, "LEARNING"), (FINISHED, "FINISHED")]

	deck = models.ForeignKey(Deck, on_delete=models.CASCADE)
	youtube = models.ForeignKey(Youtube, on_delete=models.CASCADE, null=True)
	front_text = models.TextField(max_length=500)
	back_text = models.TextField(max_length=500)
	front_img = models.ImageField(blank=True)
	back_img = models.ImageField(blank=True)
	state = models.CharField(max_length=20, choices=STATE, default=NEW)
	finished_count = models.PositiveSmallIntegerField()
	youtube_timestamp = models.TimeField()
	due_time = models.DateTimeField()


	def review_card_id_list(card_list):
		## dont keep card which is finished
		id_list = []
		for card in card_list:
			if card.state != "F":
				id_list.append(str(card.id))
		return ",".join(id_list)

	def get_card_list_by_id_list(id_list):
		if id_list == '':
			return None
		id_list = id_list.split(',')
		id_list = list(map(lambda x: int(x), id_list))
		return Card.objects.filter(pk__in=id_list)

	def earliest_card(card_list):
		min_card = card_list[0]
		for card in card_list:
			if card.due_time < min_card.due_time:
				min_card = card
		return min_card

	def get_youtube_link_with_timestamp(url, timestamp):
		minutes = timestamp.hour * 60 + timestamp.minute
		sec = timestamp.second
		suffix = "&t={}m{}s".format(minutes, sec)
		return url + suffix


	def card_list_state_count(card_list):
		count = [0, 0, 0] # REWVIEW, LEARNING, NEW
		for card in card_list:
			if card.state == NEW:
				count[2] += 1
			elif card.state == LEARNING:
				count[1] += 1
			elif card.state == REVIEW:
				count[0] += 1
		return count

	def remove_value_from_id_list(id, id_list):
		id_list = id_list.split(",")
		if str(id) in id_list:
			id_list.remove(str(id))
		return ",".join(id_list)

	def modify_cards(answer, question_id, id_list):
		card = Card.objects.get(pk=question_id)
		if answer == "<1m":
			card.due_time = timezone.now() + timedelta(minutes=1)
			card.state = "L"
		elif answer == "<10m":
			card.due_time = timezone.now() + timedelta(minutes=10)
			card.state = "L"
		elif answer == "3d":
			card.due_time = timezone.now() + timedelta(days=3)
			card.state = "F"
			id_list = Card.remove_value_from_id_list(question_id, id_list)
		card.save()
		return id_list

main/forms.py
from django import forms
from django.forms import ModelForm
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from .models import Card, Youtube, Deck

class SigninForm(forms.Form):
    username = forms.CharField(max_length=50,
                            label="",
                            widget = forms.TextInput(attrs={'placeholder': 'Username',
                                                            'class': 'textbox'}))
    password = forms.CharField(max_length=50,
                            label="",
                            widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                            'class': 'textbox'}))

class SearchForm(forms.Form):
    search_bar = forms.URLField(label = "", widget = forms.TextInput(attrs={'placeholder': "www.youbute.com"}))

    def clean_search_bar(self):
        url = self.cleaned_data['search_bar']
        val = URLValidator()
        try:
            val(url)
        except:
            msg = "Webpage does not exist"
            self.add_error(field='search_bar', error=msg)
        return url


class CardForm(forms.Form):
    deck = forms.MultipleChoiceField()

    front_text = forms.CharField(max_length=500,
                                label='',
                                widget = forms.Textarea
    )
    back_text = forms.CharField(max_length=500,
                                label='',
                                widget = forms.Textarea
    )
    youtube_timestamp = forms.TimeField()

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs);
        if user:
            deck_list = user.deck_set.all()
            options = ( (deck.id, deck.deck_name) for deck in deck_list )
            self.fields['deck'].choices = options
class YoutubeForm(ModelForm):
    class Meta:
        model = Youtube
        fields = '__all__'

class DeckForm(forms.Form):
    deck_name = forms.CharField(max_length=30)


class AnswerForm(forms.Form):
    #options = (("<1m", "<1m"), ("<10m", "<10m"), ("3d", "3d"))
    answer = forms.CharField(max_length=10)
    question_id = forms.IntegerField()

main/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth import authenticate, login
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .forms import SigninForm,  SearchForm, CardForm, YoutubeForm, DeckForm, AnswerForm
from .models import Card, Deck, Youtube
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.http import JsonResponse,  HttpResponseNotFound
import re
from datetime import datetime
from django.urls import resolve

def index(request):
	return render(request, 'main/index.html', {})



def signin(request):
	if request.method == 'POST':
		form = SigninForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(username=username, password=password)
			if user:
				login(request, user)
				return redirect(reverse('main:home'))
			else:
				form.add_error(field=None, error="invalid password or username")
	else:
		form = SigninForm()
	return render(request, 'main/signin.html', {"form": form})


def signup(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)

		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			password = form.cleaned_data['password1']
			user = authenticate(username=username, password=password)
			login(request, user)
			return redirect(reverse('main:home'))

	else:
		form = UserCreationForm()
	return render(request, 'main/signup.html', {"form": form})




@login_required(login_url="/signin/", redirect_field_name="home")
def home(request):
	user = request.user
	if request.method == 'POST':
		form = DeckForm(request.POST)
		if form.is_valid():
			deck_name = form.cleaned_data['deck_name']
			new_deck = Deck(deck_name = deck_name, user=user)
			new_deck.save()

	deck_list = user.deck_set.all()
	due_new_list = []
	for deck in deck_list:
		due_new_list.append(deck.get_due_new_num())
	zip_list = zip(deck_list, due_new_list)
	form = DeckForm()
	context = {'context': zip_list, "form": form}
	return render(request, 'main/home.html', context)


@login_required(login_url="/signin/")
def deck(request, pk):
	mydeck = Deck.objects.get(pk=pk)
	youtube_videos = mydeck.get_youtube_videos()

	return render(request, 'main/deck.html', {'context': youtube_videos, 'pk':pk})

@login_required(login_url="/signin/")
def video(request, pk):
	card_list = Youtube.objects.get(pk=pk).card_set.all()

	return render(request, 'main/video.html', {'card_list': card_list, 'pk':pk})


@login_required(login_url="/signin/")
def card(request, pk):
	card = Card.objects.get(pk=pk)
	return render(request, 'main/card.html', {'card': card})



@login_required(login_url="/signin/")
def addcard(request):
	if request.method == "POST":
		form = SearchForm(request.POST)
		if form.is_valid():
			url = form.cleaned_data["search_bar"]
			request.session['youtube_link'] = url
			return redirect(reverse('main:youtube_learning'))
	else:
		form = SearchForm()

	return render(request, 'main/addcard.html', {'form': form})


def get_embed_link(url):
	result = re.search("&list=", url)
	if result != None:
		pos = result.start()
		chopped_url = url[0:pos]
	else:
		chopped_url = url
	return re.sub("watch\?v=", "embed/", chopped_url), chopped_url



def init_card(card_form, youtube):
	value_dict = {'state': "N", 'finished_count': 0, 'due_time': datetime.now(), 'youtube': youtube}
	for key, value in card_form.cleaned_data.items():
		value_dict[key] = value
	value_dict['deck'] = Deck.objects.get(pk=value_dict['deck'][0])
	return Card(**value_dict)


@login_required(login_url="/signin/")
def youtube_learning(request):
	url = request.session.get("youtube_link")
	embed_link, url = get_embed_link(url)
	if request.method == "POST":
		card_form = CardForm(request.POST, user=request.user)
		youtube_form = YoutubeForm(request.POST)
		if youtube_form.is_valid():
			if card_form.is_valid():
				deck_id = card_form.cleaned_data['deck'][0]
				youtube_list = Deck.objects.get(pk=deck_id).youtube_set.all()
				youtube_link = youtube_form.cleaned_data["youtube_link"]
				youtube_list = youtube_list.filter(youtube_link=youtube_link)
				if len(youtube_list) != 0:
					youtube = youtube_list[0]
				else:
					youtube = youtube_form.save()
				card = init_card(card_form, youtube)
				card.save()
				return JsonResponse({'success': True});
			else:
				## card_form error
				return JsonResponse({'success': False})
		else:
			#youtube_form error
			return JsonResponse({'success': False})
	else:
		youtube_form = YoutubeForm(initial={'youtube_link': url})
		card_form = CardForm(user=request.user)

	return render(request, 'main/youtube_learning.html', {'youtube_form': youtube_form, 'card_form': card_form, "embed_link": embed_link})


@login_required(login_url="/signin/")
def review(request, type, pk):
	if type == "deck":
		deck = Deck.objects.get(pk=pk)
		card_list = deck.card_set.all()
		path = deck.deck_name
		back_path = "/home/" + str(pk) + "/"
	elif type == "video":
		youtube = Youtube.objects.get(pk=pk)
		card_list = youtube.card_set.all()
		deck = card_list[0].deck
		path = deck.deck_name + "/" + youtube.youtube_title
		back_path = "/video/" + str(pk) + "/"
	else:
		return HttpResponseNotFound('<h1>Page not found</h1>')

	(review_num, learning_num, new_num) = Card.card_list_state_count(card_list)
	context = {'review_num': review_num, 'learning_num': learning_num, 'new_num': new_num, 'path': path, 'back_path': back_path}
	request.session['review_card_list'] = Card.review_card_id_list(card_list)
	print(request.session['review_card_list'])
	if review_num == 0 and learning_num == 0 and new_num == 0:
		context["congra_msg"] = "Congratulations! You have finished all cards."
	return render(request, 'main/review.html', context)



@login_required(login_url="/signin/")
def question_answer(request):

	if request.method == "POST":
		## change the review_card_list
		form = AnswerForm(request.POST)
		if form.is_valid():
			answer = form.cleaned_data['answer']
			question_id = form.cleaned_data['question_id']
			request.session['review_card_list'] = Card.modify_cards(answer, question_id, request.session['review_card_list'])
	###prepare next question
	current_url = request.get_full_path()
	back_url = re.sub("question_answer/", "", current_url)
	if "review_card_list" in request.session:
		card_list = Card.get_card_list_by_id_list(request.session['review_card_list'])
		if card_list != None:
			card = Card.earliest_card(card_list)
			answers = (("<1m", "again"), ("<10m", "good"), ("3d", "easy"))
			youtube_link = Card.get_youtube_link_with_timestamp(card.youtube.youtube_link, card.youtube_timestamp)
			form = AnswerForm(initial={'question_id': card.id})
			context = {'card': card, 'back_url':back_url, 'answers': answers, "youtube_link":youtube_link, 'form': form}
			return render(request, 'main/question_answer.html', context)

	return redirect(back_url)


def signout(request):
	logout(request)
	return redirect(reverse('main:index'))

main/templates/main/addcard.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Rewind</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'main/addcard.css' %}">
    </head>

    <body>
        <aside>
            <div class="logo_div">
                {% if user.is_authenticated %}
                    <a href="{% url 'main:home' %}"><img class="logo" src="{% static 'main/images/Big_icon.svg' %}" alt="Rewind Logo"></a>
                {% else %}
                    <a href="{% url 'main:index' %}"><img class="logo" src="{% static 'main/images/Big_icon.svg' %}" alt="Rewind Logo"></a>
                {% endif %}
            </div>
            <div class="aside_btn">
                <ul>
                    <li><a href="{% url 'main:addcard' %}"><button>Add</button></a></li>
                    <li><a href="{% url 'main:home' %}"><button>Decks</button></a></li>
                    <li><button>Statistic</button></li>
                </ul>
            </div>

        </aside>
        <header>
            <button class="back"><img src="{% static 'main/images/back.svg' %}" alt="back to previous"></button>
        </header>
        <main>
            <div class="search">
                <form action="/addcard/", method="POST">
                    {% csrf_token %}
                    <label for="{{ form.search_bar.id_for_label }}" >Video Learning:</label>
                    <img src="{% static 'main/images/search_icon.svg' %}">
                    {{ form.search_bar }}
                    {{ form.search_bar.errors }}
                    <button type="submit"></button>

                </form>
                <p>Please enter the youtube video link</p>

            </div>

            <!--
            <div class="middle_content">

                <div class="card">
                    <label for="front">Front</label><br>
                    <textarea id="front" rows="8" cols="60" name="front">aaaa</textarea><br>


                    <label for="back">Back</label><br>
                    <textarea id="back" rows="8" cols="60" name="back">eeee</textarea><br>
                </div>

            </div>
            <div class="deck">
                <select id="decks" name="decks">
                    <option value="deck1">deck1</option>
                    <option value="deck2">deck2</option>
                </select>

            </div>
        -->
        </main>
    </body>

</html>

main/templates/main/deck.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Rewind</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'main/deck.css' %}">
    </head>

    <body>
        <aside>
            <div class="logo_div">
                {% if user.is_authenticated %}
                    <a href="{% url 'main:home' %}"><img class="logo" src="{% static 'main/images/Big_icon.svg' %}" alt="Rewind Logo"></a>
                {% else %}
                    <a href="{% url 'main:index' %}"><img class="logo" src="{% static 'main/images/Big_icon.svg' %}" alt="Rewind Logo"></a>
                {% endif %}
            </div>
            <div class="aside_btn">
                <ul>
                    <li><a href="{% url 'main:addcard' %}"><button>Add</button></a></li>
                    <li><a href="{% url 'main:home' %}"><button>Decks</button></a></li>
                    <li><button>Statistic</button></li>
                </ul>
            </div>

            <div class="study_now_btn">
                <a href="/review/deck/{{ pk }}/"><button  type="button" name="study now">Study Now</button></a>
            </div>
        </aside>
        <header>
            <a href="{% url 'main:home' %}"class="back"><img src="{% static 'main/images/back.svg' %}" alt="back to previous"></a>
        </header>
        <main>
            <div class="decks_table">
                <table align="center">
                    <thead>
                        <tr>
                            <th>Video</th>
                            <th>Due</th>
                            <th>New</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in context %}
                            <tr>
                                <td><a href="{% url 'main:index' %}video/{{ item.0.id }}">
                                    <span><img src="{% static 'main/images/video_icon.svg' %}" alt="card icon"></span>
                                    {{ item.0.youtube_title }}</a></td>
                                <td>{{ item.1 }}</td>
                                <td>{{ item.2 }}</td>
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </main>
    </body>

</html>

main/templates/main/home.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Rewind</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'main/home.css' %}">
    </head>

    <body>
        <aside>
            <div class="logo_div">
                {% if user.is_authenticated %}
                    <a href="{% url 'main:home' %}"><img class="logo" src="{% static 'main/images/Big_icon.svg' %}" alt="Rewind Logo"></a>
                {% else %}
                    <a href="{% url 'main:index' %}"><img class="logo" src="{% static 'main/images/Big_icon.svg' %}" alt="Rewind Logo"></a>
                {% endif %}
            </div>
            <div class="aside_btn">
                <ul>
                    <li><a href="{% url 'main:addcard' %}"><button>Add</button></a></li>
                    <li><a href="{% url 'main:home' %}"><button>Decks</button></a></li>
                    <li><button>Statistic</button></li>
                    <li><button onclick="confirm_logout()" >Logout</button></li>
                </ul>
            </div>

        </aside>
        <header>

        </header>
        <main>
            <div style="display:none;visibility:hidden;">
                <form id="deck_form" method='post'>
                    {% csrf_token %}
                    {{ form.deck_name }}
                </form>
            </div>
            <p>{{ form.deck_name.errors }}</p>
            <div class="decks_table">
                <table align="center">
                    <thead>
                        <tr>
                            <th>Decks</th>
                            <th>Due</th>
                            <th>New</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in context %}
                            <tr>
                                <td><span><a href="{% url 'main:deck' item.0.id %}"><img src="{% static 'main/images/card_icon.svg' %}" alt="card icon">
                                </span>{{ item.0.deck_name }}</a>
                            </td>
                                <td>{{ item.1.0}}</td>
                                <td>{{ item.1.1}}</td>
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
            <div class="create_btn">
                <button onclick="create_deck()">Create Deck</button>
            </div>
        </main>
    </body>
    <script>
    function create_deck() {
        var deck_name = prompt("Please enter your deck name:");
        if (deck_name != null && deck_name != "") {
            document.getElementById("id_deck_name").value = deck_name;
            document.getElementById("deck_form").submit();
        }

    }

    function confirm_logout(){
        console.log("hihi");
        var response = confirm("Are you sure to logout?");
        if (response == true){
            window.location = "/signout/";
        }
    }
    </script>

</html>

main/templates/main/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rewind</title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/index.css' %}">

</head>

<body style="background-image: url({% static 'main/images/bgi.jpg' %});">
    <header>
        <div>
            {% if user.is_authenticated %}
                <a href="{% url 'main:home' %}"><img class="logo" src="{% static 'main/images/Big_icon.svg' %}" alt="Rewind Logo"></a>
            {% else %}
                <a href="{% url 'main:index' %}"><img class="logo" src="{% static 'main/images/Big_icon.svg' %}" alt="Rewind Logo"></a>
            {% endif %}
        </div>
        <div>
            <ul>
                <li><a href="{% url 'main:signin' %}">Sign In</a></li>
                <li><a href="{% url 'main:signup' %}">Sign Up</a></li>
            </ul>
        </div>
    </header>
    <main>

        <h1>Rewind</h1>
        <p>A learning tool that help you make flash card for Youtube video. You will never forget what you have learned in Youtube. Inspired by Anki.</p>
        <div>
            <img class="youtube_icon" src="{% static 'main/images/youtube_icon.svg' %}" alt="youtube icon">
        </div>

        <div class="card_container">
            <div class="card">
                <div class="front_card">
                    <img  src="{% static 'main/images/front_card.svg' %}" alt="front card">
                </div>
                <div class="back_card">
                    <img  src="{% static 'main/images/backcard.svg' %}" alt="back card">
                </div>

            </div>
        </div>

    </main>
</body>
</html>

main/templates/main/signin.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rewind</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/signin.css' %}">
</head>

<body style="background-image: url({% static 'main/images/bgi.jpg' %});">
    <header>
        <div>
            {% if user.is_authenticated %}
                <a href="{% url 'main:home' %}"><img class="logo" src="{% static 'main/images/Big_icon.svg' %}" alt="Rewind Logo"></a>
            {% else %}
                <a href="{% url 'main:index' %}"><img class="logo" src="{% static 'main/images/Big_icon.svg' %}" alt="Rewind Logo"></a>
            {% endif %}
        </div>
    </header>
    <main>

        <div class="Signin-box">

            <h1>Sign In</h1>
            <form action="/signin/" method="post">
                {% csrf_token %}

                {{ form }}

                <input type="submit" class="btn" name="submit_btn" value="Sign In">

                <p>No account? <a href="{% url 'main:signup' %}" >Sign up</a> now!</p>
            </form>

        </div>



    </main>
</body>


</html>

main/templates/main/youtube_learning.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Rewind</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'main/youtube_learning.css' %}">
    </head>

    <body>
        <aside>
            <div>
                <iframe id="youtube-video" width="560" height="315" src="{{ embed_link }}?enablejsapi=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>

        </aside>
        <header>
            <a href="{% url 'main:addcard' %}"><button class="back"><img src="{% static 'main/images/back.svg' %}" alt="back to previous"></button></a>
        </header>
        <main>
            <div class="Title">
                <p>Youtube Link: {{ youtube_form.youtube_link.value }}</p>
                <p>Title: <span id="youtube-title"></span></p>
                <div id="success_msg"></div>
            </div>
            <form action="/youtube_learning/" method="post" id="addcard-form">
                {% csrf_token %}
                <div class="hidden-input">
                    {{ youtube_form.youtube_link }}
                    {{ youtube_form.youtube_title }}
                </div>

                <div class="middle_content">
                    <div class="screenshot">
                        <button type="button"><img src="{% static 'main/images/screenshot_icon.svg' %}"></button>
                    </div>
                    <div class="card">
                        <label for="front">Front</label><br>
                        <!--<textarea id="front" rows="8" cols="60" name="front"></textarea><br>-->
                        {{ card_form.front_text }}<br>
                        <label for="back">Back</label><br>
                        {{ card_form.back_text }}<br>
                        <!--<textarea id="back" rows="8" cols="60" name="back"></textarea><br>-->
                    </div>

                </div>
                <div class="timestamp">
                    <div>
                        <p>timestamp: <span id="current-time">00:00:00</span></p>
                        <div class="hidden-input">
                            {{ card_form.youtube_timestamp }}
                        </div>
                    </div>
                    <div>
                        <button type="button" onclick = "get_time()" >Current Video Time</button>
                    </div>
                </div>

                <div class="deck">
                    <select id="id_deck" name="deck">
                        {% for deck in card_form.deck %}
                            {{ deck }}
                         {% endfor %}

                    </select>
                    {{ card_form.deck.errors }}
                </div>

                <div class="add">
                    <button type="submit">ADD</button>
                </div>
            </form>
        </main>

    </body>
    <script type="text/jscript" src="{% static 'main/js/jquery.min.js' %}"></script>
    <script src="https://www.youtube.com/iframe_api"></script>
    <script src="{% static 'main/js/main.js' %}"></script>

    <script type="text/javascript">

    function delete_success_msg(){
        var element = document.getElementById("success_msg");
        element.innerHTML = '';
    }

    function show_success_msg(msg){
        var tag = document.createElement("p");
        var text = document.createTextNode(msg);
        tag.appendChild(text);
        var element = document.getElementById("success_msg");
        element.append(tag);

        setTimeout(delete_success_msg, 2500);
    }

    function create_card() {

        console.log("create post is working!") // sanity check
        $.ajax({
            url: '/youtube_learning/',
            type: 'POST',
            data: {
                youtube_link: $('#id_youtube_link').val(),
                youtube_title: $('#id_youtube_title').val(),
                front_text: $('#id_front_text').val(),
                back_text: $('#id_back_text').val(),
                youtube_timestamp: $('#id_youtube_timestamp').val(),
                deck: $('#id_deck').val()
            },
            success: function(json){
                $('#id_front_text').val('');
                $('#id_back_text').val('');
                let msg = "successfuly add card";
                show_success_msg(msg);

            },

            error: function(json){
                let msg = "fail to add card";
                show_success_msg(msg);
            }
        });
    }

        $(document).on('submit', "#addcard-form", function(event){
            event.preventDefault();
            create_card();
        });
    </script>

    <script>
    var player;
    function onYouTubeIframeAPIReady() {
      player = new YT.Player('youtube-video', {
        events: {
          'onReady': onPlayerReady,
          'onStateChange': onPlayerStateChange,
        }
      });
    }



    function onPlayerReady() {
        console.log("hey Im ready");
        var title = player.getVideoData().title;
        document.getElementById("youtube-title").innerHTML = title;
        document.getElementById("id_youtube_title").value = title;
        document.getElementById("id_youtube_timestamp").value = "00:00:00";
    }

    function onPlayerStateChange() {
        console.log("my state changed");
    }

    function get_time() {
        let time = player.getCurrentTime();
        let hour = Math.floor(time / 3600);
        let min = Math.floor((time % 3600) / 60);
        let sec = Math.floor((time % 3600 % 60));
        let time_string = hour.toString().padStart(2, '0') + ":" + min.toString().padStart(2, '0')  + ":" + sec.toString().padStart(2, '0');
        var element = document.getElementById("current-time");
        element.innerHTML = time_string;
        document.getElementById("id_youtube_timestamp").value = time_string;
    }


    </script>


</html>